# -*- coding: utf-8 -*-
path = r'C:\Users\jdsds\Desktop\Projetos\portfolio\app\projetos\rpg-chronicle\page.tsx'
content = open(path, 'r', encoding='utf-8').read()

replacements = [
    ('"O Inicio"', '"O Início"'),
    ('"Distrito da Saude"', '"Distrito da Saúde"'),
    ('"Laboratorio"', '"Laboratório"'),
    ('"Cacarola"', '"Caçarola"'),
    ('"Cafe Praca 18"', '"Café Praça 18"'),
    ('"O cafe iconico da praca"', '"O café icónico da praça"'),
    ('"Marisco fresco ha geracoes"', '"Marisco fresco há gerações"'),
    ('"Surf cafe a beira-mar"', '"Surf café à beira-mar"'),
    ('"Sabor Abencoado"', '"Sabor Abençoado"'),
    ('"Pizza napolitana autentica"', '"Pizza napolitana autêntica"'),
    ('"Tapas com espetaculo"', '"Tapas com espetáculo"'),
    ('"Pe na Areia"', '"Pé na Areia"'),
    ('"Cozinha de autor historica"', '"Cozinha de autor histórica"'),
    ('"Maregrafo"', '"Marégrafo"'),
    ('"Fine dining a beira-mar"', '"Fine dining à beira-mar"'),
    ('"Enoteca & degustacao"', '"Enoteca & degustação"'),
    ('"O dentista das criancas"', '"O dentista das crianças"'),
    ('"Clinica Vasco da Gama"', '"Clínica Vasco da Gama"'),
    ('"Foco em prevencao"', '"Foco em prevenção"'),
    ('"Clinica Tamargueira"', '"Clínica Tamargueira"'),
    ('"Clinica de Quiaios"', '"Clínica de Quiaios"'),
    ('"Familiar e acessivel"', '"Familiar e acessível"'),
    ('"Alba Saude"', '"Alba Saúde"'),
    ('"Estetica dental moderna"', '"Estética dental moderna"'),
    ('"Bateria electronica"', '"Bateria eletrónica"'),
    ('"Caixinha de musica"', '"Caixinha de música"'),
    ('"Arte generativa com codigo"', '"Arte generativa com código"'),
    ('"Xadrez classico"', '"Xadrez clássico"'),
    ('"O classico jogo da cobra"', '"O clássico jogo da cobra"'),
    ('"Jogo da memoria"', '"Jogo da memória"'),
    ('"Quao bem conheces PT?"', '"Quão bem conheces PT?"'),
    ('"Mistura emojis unicos"', '"Mistura emojis únicos"'),
    ('"Testa expressoes regulares"', '"Testa expressões regulares"'),
    ('"Rastreador de habitos"', '"Rastreador de hábitos"'),
    ('"Cartoes de memoria"', '"Cartões de memória"'),
    ('"Roda de decisoes"', '"Roda de decisões"'),
    ('"Diario de humor diario"', '"Diário de humor"'),
    ('"Teste de velocidade de digitacao"', '"Teste de velocidade de digitação"'),
    ('"Tradutor de codigo Morse"', '"Tradutor de código Morse"'),
    ('"Exercicios de respiracao"', '"Exercícios de respiração"'),
    ('"Calculadora cientifica"', '"Calculadora científica"'),
    ('"Tabela periodica interativa"', '"Tabela periódica interativa"'),
    ('"Simulador de particulas"', '"Simulador de partículas"'),
    ('"Relogios mundiais"', '"Relógios mundiais"'),
    ('Musica"', 'Música"'),
    ('Ciencia"', 'Ciência"'),
    ('Experiencias"', 'Experiências"'),
    ('Inicio do caminho', 'Início do caminho'),
    ('Experiencia em startup', 'Experiência em startup'),
    ('Foco em IA e automacao', 'Foco em IA e automação'),
    ('MSc concluido', 'MSc concluído'),
    ('109 paginas numa noite. O futuro e agora.', '109 páginas numa noite. O futuro é agora.'),
    ('"Primeiro Capitulo"', '"Primeiro Capítulo"'),
    ('Scrollar para la do Capitulo', 'Scrollar para lá do Capítulo'),
    ('"Leitor Avido"', '"Leitor Ávido"'),
    ('Explorar todos os 8 capitulos', 'Explorar todos os 8 capítulos'),
    ('Completar todos os capitulos em menos de 2 minutos', 'Completar todos os capítulos em menos de 2 minutos'),
    ('"Noctambulo"', '"Noctâmbulo"'),
    ('"Volta ao Inicio"', '"Volta ao Início"'),
    ('Usar o botao de voltar ao topo', 'Usar o botão de voltar ao topo'),
    ('Quem nao arrisca, nao petisca!', 'Quem não arrisca, não petisca!'),
    ('A pressa e inimiga da perfeicao.', 'A pressa é inimiga da perfeição.'),
    ('De grao em grao, enche a galinha o papo.', 'De grão em grão, enche a galinha o papo.'),
    ('Mais vale um passaro na mao do que dois a voar.', 'Mais vale um pássaro na mão do que dois a voar.'),
    ('O saber nao ocupa lugar.', 'O saber não ocupa lugar.'),
    ('Cada cabeca, sua sentenca.', 'Cada cabeça, sua sentença.'),
    ('Agua mole em pedra dura', 'Água mole em pedra dura'),
    ('inteligencia artificial', 'inteligência artificial'),
    ('109 Paginas', '109 Páginas'),
    ('Desce para comecar', 'Desce para começar'),
    ('Instituto Superior Tecnico', 'Instituto Superior Técnico'),
    ('A tecnologia e o meio, nao o fim.', 'A tecnologia é o meio, não o fim.'),
    ('"Vida Autentica"', '"Vida Autêntica"'),
    ('codigo com proposito', 'código com propósito'),
    ('"Amor no Codigo"', '"Amor no Código"'),
    ('Cada linha escrita com intencao.', 'Cada linha escrita com intenção.'),
    ('O futuro e humano.', 'O futuro é humano.'),
    ('Ola! Sou o Jaime.', 'Olá! Sou o Jaime.'),
    ('Paginas criadas', 'Páginas criadas'),
    ('Linhas de codigo', 'Linhas de código'),
    ('Estas sao as ferramentas', 'Estas são as ferramentas'),
    ('Outras competencias', 'Outras competências'),
    ('Satisfacao dos clientes', 'Satisfação dos clientes'),
    ('"Satisfacao"', '"Satisfação"'),
    ('"Repeticao"', '"Repetição"'),
    ('Memoria de Sabores', 'Memória de Sabores'),
    ('jogo de memoria', 'jogo de memória'),
    ('Parabens!', 'Parabéns!'),
    ('Diagnostico de problemas', 'Diagnóstico de problemas'),
    ('"Diagnostico Digital"', '"Diagnóstico Digital"'),
    ('a solucao correta', 'à solução correta'),
    ('jogo de diagnostico', 'jogo de diagnóstico'),
    ('Diagnostico completo!', 'Diagnóstico completo!'),
    ('clica na solucao', 'clica na solução'),
    ('Desafio de codigo', 'Desafio de código'),
    ('o mais rapido possivel', 'o mais rápido possível'),
    ('desafio de codigo', 'desafio de código'),
    ('Concluido!', 'Concluído!'),
    ('"Precisao"', '"Precisão"'),
    ('O futuro e humano. Keep building.', 'O futuro é humano. Keep building.'),
    ('comando nao encontrado', 'comando não encontrado'),
    ('Exploracao Completa!', 'Exploração Completa!'),
    ('Saltar para o capitulo', 'Saltar para o capítulo'),
    ('Fechar dialogo', 'Fechar diálogo'),
    ('O codigo esta vivo!', 'O código está vivo!'),
    ('8 clinicas digitalizadas', '8 clínicas digitalizadas'),
    ('ferramentas e experiencias interativas', 'ferramentas e experiências interativas'),
    ('Cada ponto e uma historia. Esta jornada e so o comeco.', 'Cada ponto é uma história. Esta jornada é só o começo.'),
    ('Sites modernos, rapidos e responsivos', 'Sites modernos, rápidos e responsivos'),
    ('Identidade visual completa para o teu negocio', 'Identidade visual completa para o teu negócio'),
    ('Aplicacoes interativas e ferramentas personalizadas', 'Aplicações interativas e ferramentas personalizadas'),
    ('"Automacao"', '"Automação"'),
    ('Estrategia digital e optimizacao de processos', 'Estratégia digital e otimização de processos'),
    ('"Paginas"', '"Páginas"'),
    ('"Clinicas"', '"Clínicas"'),
    ('Tudo construido com paixao', 'Tudo construído com paixão'),
    ('Voltar ao inicio', 'Voltar ao início'),
    ('Recem chegaste', 'Recém chegaste'),
    ('Distancia Scrollada', 'Distância Scrollada'),
    ('Tempo de Exploracao', 'Tempo de Exploração'),
    ('Capitulos Explorados', 'Capítulos Explorados'),
    ('"Estatisticas"', '"Estatísticas"'),
    ('Capitulos explorados', 'Capítulos explorados'),
    ('de exploracao', 'de exploração'),
    ('Capitulo favorito', 'Capítulo favorito'),
    ('A TUA JORNADA EM NUMEROS', 'A TUA JORNADA EM NÚMEROS'),
    ('Recomecar', 'Recomeçar'),
    ('Em breve: Experiencia com som', 'Em breve: Experiência com som'),
    ('"experiencias"', '"experiências"'),
]

count = 0
for old, new in replacements:
    if old in content and old != new:
        content = content.replace(old, new)
        count += 1

open(path, 'w', encoding='utf-8').write(content)
print(f"Applied {count} accent fixes to RPG Chronicle")
